---
title: "Classification"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(mlbench)
data(Glass)
library(ggplot2)
library(class)
library(caret)
library(e1071)
```

1. Boxplots

```{r}
qplot(data = Glass, y = RI, color = Type, geom = "boxplot", main = "Refractive Index")
```
```{r}
qplot(data = Glass, y = Na, color = Type, geom = "boxplot", main = "Na")
```
```{r}
qplot(data = Glass, y = Mg, color = Type, geom = "boxplot", main = "Mg")
```
```{r}
qplot(data = Glass, y = Al, color = Type, geom = "boxplot", main = "Al")
```
```{r}
qplot(data = Glass, y = Si, color = Type, geom = "boxplot", main = "Si")
```
```{r}
qplot(data = Glass, y = K, color = Type, geom = "boxplot", main = "K")
```
```{r}
qplot(data = Glass, y = Ca, color = Type, geom = "boxplot", main = "Ca")
```
```{r}
qplot(data = Glass, y = Ba, color = Type, geom = "boxplot", main = "Ba")
```
```{r}
qplot(data = Glass, y = Fe, color = Type, geom = "boxplot", main = "Fe")
```

2. KNN

a. Al

```{r}
set.seed(42)
# Stratified sampling
test <- createDataPartition(Glass$Type, p=0.25, list = FALSE)

pred_knn <- knn(train = Glass[-test, "Al", drop = FALSE],
                test = Glass[test, "Al", drop = FALSE],
                
                cl = Glass[-test, "Type"],
                k = 1)

table(pred_knn, Real = Glass[test, "Type"])
mean(pred_knn == Glass[test, "Type"])
```

```{r}
set.seed(42)
pred_knn <- knn(train = Glass[-test, "Al", drop = FALSE],
                test = Glass[test, "Al", drop = FALSE],
                
                cl = Glass[-test, "Type"],
                k = 10)

table(pred_knn, Real = Glass[test, "Type"])
mean(pred_knn == Glass[test, "Type"])
```

k-fold cross val

```{r}
set.seed(42)

trControl <- trainControl(method  = "cv",
                          number  = 12)
fit <- train(Type ~ Al,
             method     = "knn",
             tuneGrid   = expand.grid(k = 1:20),
             trControl  = trControl,
             metric     = "Accuracy",
             data       = Glass)
```
```{r}
fit
```

```{r}
plot(fit)
```

b. RI, Al, Si

```{r}
set.seed(42)
pred_knn <- knn(train = Glass[-test, c("RI","Al","Si")],
                test = Glass[test, c("RI","Al","Si")],
                
                cl = Glass[-test, "Type"],
                k = 1)

table(pred_knn, Real = Glass[test, "Type"])
mean(pred_knn == Glass[test, "Type"])
```

```{r}
set.seed(42)

trControl <- trainControl(method  = "cv",
                          number  = 12)

fit <- train(Type ~ RI + Al + Si,
             method     = "knn",
             tuneGrid   = expand.grid(k = 1:20),
             trControl  = trControl,
             metric     = "Accuracy",
             data       = Glass)
```
```{r}
fit
```

```{r}
plot(fit)
```

c. All possible predictors

```{r}
set.seed(42)
pred_knn <- knn(train = Glass[-test, c("RI","Na","Mg" ,"Al","Si", "K", "Ca","Ba","Fe")],
                test = Glass[test, c("RI","Na","Mg" ,"Al","Si", "K", "Ca","Ba","Fe")],
                
                cl = Glass[-test, "Type"],
                k = 1)

table(pred_knn, Real = Glass[test, "Type"])
mean(pred_knn == Glass[test, "Type"])
```

```{r}
set.seed(42)

trControl <- trainControl(method  = "cv",
                          number  = 12)

fit <- train(Type ~ RI + Na + Mg + Al + Si + K + Ca + Ba + Fe,
             method     = "knn",
             tuneGrid   = expand.grid(k = 1:20),
             trControl  = trControl,
             metric     = "Accuracy",
             data       = Glass)
fit
```

```{r}
plot(fit)
```

d. with PCA

```{r}
pca.result <- prcomp(Glass[-test,-c(10:11)], scale=T)
train.pca <- pca.result$x
test.pca <- predict(pca.result, Glass[test,-c(10:11)])

k <- NULL
accuracy <- NULL
set.seed(42)
for (i in 1:20){
  pred_knn <- knn(train.pca, test.pca, Glass[-test, "Type"], k=i)
  accuracy <- c(accuracy, mean(pred_knn == Glass[test, "Type"]))
  k <- c(k, i)
}
result <- data.frame('k' = k, 'Accuracy' = accuracy)

```
```{r}
result
```

```{r}
plot(result, type = 'l')
```


```{r}
result[which.max(result$Accuracy),]
```


e. Comparing all the models

```{r echo=FALSE}
data.frame('Model' = c('Al','RI + Al + Si','All predictors','PCA' ), 'Accuracy'= c(0.5919404, 0.6233678,  0.7400707, 0.6842105))
```

3. Logistic regression

"RI"

```{r}
glm_fit_ri <- glm(Type ~ RI, data = Glass,
                  family = "binomial")
summary(glm_fit_ri)
```

"Na"

```{r}
glm_fit_na <- glm(Type ~ Na, data = Glass,
                  family = "binomial")
summary(glm_fit_na)
```

"Mg"

```{r}
glm_fit_mg <- glm(Type ~ Mg, data = Glass,
                  family = "binomial")
summary(glm_fit_mg)
```

"Al"

```{r}
glm_fit_al <- glm(Type ~ Al, data = Glass,
                  family = "binomial")
summary(glm_fit_al)
```

"Si"

```{r}
glm_fit_si <- glm(Type ~ Si, data = Glass,
                  family = "binomial")
summary(glm_fit_si)
```

"K" 

```{r}
glm_fit_k <- glm(Type ~ K, data = Glass,
                  family = "binomial")
summary(glm_fit_k)
```

"Ca"

```{r}
glm_fit_ca <- glm(Type ~ Ca, data = Glass,
                  family = "binomial")
summary(glm_fit_ca)
```

"Ba"
```{r}
glm_fit_ba <- glm(Type ~ Ba, data = Glass,
                  family = "binomial")
summary(glm_fit_ba)
```

"Fe"

```{r}
glm_fit_fe <- glm(Type ~ Fe, data = Glass,
                  family = "binomial")
summary(glm_fit_fe)
```

"All predictors"

```{r}
glm_fit_all <- glm(Type ~ RI + Na + Mg + Al + Si + K + Ca + Ba + Fe , data = Glass,
                  family = "binomial")
summary(glm_fit_all)
```

"Best"

```{r}
glm_fit_best <- glm(Type ~ Mg + Al + Si , data = Glass,
                  family = "binomial")
summary(glm_fit_best)
```

Transfromation

```{r}
one <- Glass$Mg
two <-  Glass$Al^2
three <- Glass$Si^3

glm_fit_transf <- glm(Type ~ one + two + three , data = Glass,
                    family = "binomial")
summary(glm_fit_transf)
```

```{r}
glm_fit_transf2 <- glm(Type ~ Mg + Al + Si , data = Glass[-test,],
                    family = "binomial")
pred_glm <- predict(glm_fit_transf2, type = "response", newdata = Glass[test, ]) > .5
table(pred_glm, Real = Glass[test, 10])
```




```{r}
16/20
```

