library (tidyr)
library (dplyr)
library (lubridate)
  data <- readRDS('/home/dmitrii/Projects/R_stat/weather')
  data1 <- select(data, -1)
  data1 <- gather(data1, day, parameter, X1:X31, na.rm = TRUE)
  data1$day <- gsub(pattern = "X", replacement = "", x = data1$day, ignore.case = T)
  data1 <- mutate(data1, parameter=ifelse(parameter=='', 'no_event', parameter))
  data1 <- unite(data1, date, day, month, year, sep='-')
  data1$date <-dmy(data1$date)
  data1 <- spread(data1, measure, parameter)
  data1[,-c(1,3,22)] <- sapply(data1[, -c(1,3,22)], as.numeric)
  data1[c(4:21,23)] <- sapply(c(4:21,23), function(x) replace(data1[,x], which(is.na(data1[,x])), mean(data1[,x], na.rm =T)))
  data1$PrecipitationIn <- data1$PrecipitationIn %>% replace(data1$PrecipitationIn == 'T', 'NA')
  