---
title: "Task 1"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(corrplot)
```

## Anscombe’s data set

• Scatter plot facetted by set

```{r}
data <- data.frame('x' = c(anscombe$x1, anscombe$x2, anscombe$x3, anscombe$x4), 
                   'y' = c(anscombe$y1, anscombe$y2, anscombe$y3, anscombe$y4),
                   'set' =  rep(c(1:4), each = 11))
ggplot(data, aes(x, y)) +
  geom_point() +
  facet_wrap(~ set)
```

• Summary calculation (mean, sd) grouped by set

```{r}
setNames(aggregate(data[, 1:2], list(data$set), mean), c('set', 'mean_x', 'mean_y'))

```

```{r}
setNames(aggregate(data[, 1:2], list('Sd' = data$set), sd),  c('set', 'sd_x', 'sd_y'))
```

• Pearson’s correlation by set, and non-parametric, and p-value

```{r message=FALSE, warning=FALSE}
data %>% group_by(set) %>% summarise(cor_pearson = cor.test(x,y, method = 'pearson')$estimate, 
                                      cor_kendall = cor.test(x,y, method = 'kendall')$estimate,
                                      cor_spearmen = cor.test(x,y, method = 'spearman')$estimate)
```

```{r message=FALSE, warning=FALSE}
data %>% group_by(set) %>% summarise(p_pearson = cor.test(x,y, method = 'pearson')$p.value,
                                     p_kendall = cor.test(x,y, method = 'kendall')$p.value,
                                     p_spearmen = cor.test(x,y, method = 'spearman')$p.value)

                                   
```

• Add geom_smooth() to the plot

```{r}
ggplot(data, aes(x, y)) +
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~ set) 
```



