library(data.table)
library(anchors)
library (tidyr)
library (dplyr)
library (lubridate)

weather <- readRDS("/Users/Lisa/Downloads/weather (1).rds")
weather1 <- dplyr::select(weather, -1)
weather2 <- gather(weather1 , day, val, X1:X31, na.rm = TRUE)
weather3 <- mutate(weather2, val=ifelse(val=='', 'no_event', val))
weather2_x_rem <-  weather3 %>% separate(day, c('del', 'day'), sep ='X')
weather_common <- unite(weather2_x_rem, date, year, month, day, sep = "-")
weather_common$date <- as.Date(gsub("X", "", weather_common$date))
final_df = pivot_wider(weather_common, id_cols = date, names_from = measure, values_from = val)
final_df$PrecipitationIn <- final_df$PrecipitationIn %>% replace(final_df$PrecipitationIn == 'T', '-1')
final_df <- final_df %>% mutate(PrecipitationIn = as.numeric(PrecipitationIn))
new_values <- final_df %>% mutate_at( -22, as.numeric) 
str(new_values)
View(new_values)

